### ISSUE TITLE
Add support to use previous parameter value

### ISSUE THREAD

**Issue by hmeltaus** [webscale-oy/bauble#8]
It should be possible to use previous parameter value when a stack is updated.

Configuration could look something like this:

```
parameters:
  foo:
    value: bar
    usePreviousValue: true
```
